# Autogenerated file, do not modify it!!!

contributors = [
  "marticliment",
  "skanda890",
  "ppvnf",
  "panther7",
  "Saibamen",
  "RavenMacDaddy",
  "Mikey1993",
  "flatron4eg",
  "Malus-risus",
  "gnerkus",
  "raghavdhingra24",
  "adripo",
  "mapi68",
  "MisterEvans78",
  "CoolSpy3",
  "Schtenk",
  "rumplin",
  "turw41th",
  "uKER",
  "sklart",
  "SpaceTimee",
  "aaronliu0130",
  "elliot-100",
  "mvaneijken"
]

contributorsInfo = [
  {
    "name": "marticliment",
    "link": "https://github.com/marticliment",
    "contributions": 3844
  },
  {
    "name": "skanda890",
    "link": "https://github.com/skanda890",
    "contributions": 130
  },
  {
    "name": "ppvnf",
    "link": "https://github.com/ppvnf",
    "contributions": 96
  },
  {
    "name": "panther7",
    "link": "https://github.com/panther7",
    "contributions": 71
  },
  {
    "name": "Saibamen",
    "link": "https://github.com/Saibamen",
    "contributions": 40
  },
  {
    "name": "RavenMacDaddy",
    "link": "https://github.com/RavenMacDaddy",
    "contributions": 21
  },
  {
    "name": "Mikey1993",
    "link": "https://github.com/Mikey1993",
    "contributions": 15
  },
  {
    "name": "flatron4eg",
    "link": "https://github.com/flatron4eg",
    "contributions": 13
  },
  {
    "name": "Malus-risus",
    "link": "https://github.com/Malus-risus",
    "contributions": 8
  },
  {
    "name": "gnerkus",
    "link": "https://github.com/gnerkus",
    "contributions": 8
  },
  {
    "name": "raghavdhingra24",
    "link": "https://github.com/raghavdhingra24",
    "contributions": 7
  },
  {
    "name": "adripo",
    "link": "https://github.com/adripo",
    "contributions": 6
  },
  {
    "name": "mapi68",
    "link": "https://github.com/mapi68",
    "contributions": 4
  },
  {
    "name": "MisterEvans78",
    "link": "https://github.com/MisterEvans78",
    "contributions": 4
  },
  {
    "name": "CoolSpy3",
    "link": "https://github.com/CoolSpy3",
    "contributions": 3
  },
  {
    "name": "Schtenk",
    "link": "https://github.com/Schtenk",
    "contributions": 3
  },
  {
    "name": "rumplin",
    "link": "https://github.com/rumplin",
    "contributions": 3
  },
  {
    "name": "turw41th",
    "link": "https://github.com/turw41th",
    "contributions": 3
  },
  {
    "name": "uKER",
    "link": "https://github.com/uKER",
    "contributions": 3
  },
  {
    "name": "sklart",
    "link": "https://github.com/sklart",
    "contributions": 3
  },
  {
    "name": "SpaceTimee",
    "link": "https://github.com/SpaceTimee",
    "contributions": 3
  },
  {
    "name": "aaronliu0130",
    "link": "https://github.com/aaronliu0130",
    "contributions": 2
  },
  {
    "name": "elliot-100",
    "link": "https://github.com/elliot-100",
    "contributions": 2
  },
  {
    "name": "mvaneijken",
    "link": "https://github.com/mvaneijken",
    "contributions": 2
  }
]